server:
  port: 3002

  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: demo
  cloud:
    config:
      enabled: false
  redis:
    host: 127.0.0.1 # Redis 服务器地址
    port: 6379 # Redis 服务器端口
    password: 123456 # Redis 连接密码
    database: 15 # 使用的数据库索引
    timeout: 10000 # 连接超时时间（毫秒）
    key-prefix: "cloud:" # Redis key 前缀
    lettuce: # Lettuce 连接池配置
      pool:
        max-active: 32        # 最大连接数
        max-idle: 16          # 最大空闲连接数
        min-idle: 8           # 最小空闲连接数

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

feign:
  system:
    url: 127.0.0.1:3001
    path: /system