server:
  port: 3002

  servlet:
    context-path: /demo

spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: demo
  cloud:
    config:
      enabled: false

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

feign:
  system:
    url: 127.0.0.1:3001/system/